---
# file: webservers.yml
- hosts: webservers
  remote_user: root
  sudo: yes
  roles:
    - common
    - webtier
  vars_prompt:
    - name: ssl_passphrase
      prompt: "Enter SSL Certificate Passphrase"
      private: false
